name: AI Test Writer

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-test-writer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements/ai-test-writer.txt

      - name: Run coverage
        run: |
          coverage run -m pytest
          coverage json

      - name: Run AI Test Writer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/ai_test_writer.py
