name: Check Secrets

on: workflow_dispatch

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Secret
        run: echo "${{ secrets.OPENAI_API_KEY }}"

      - name: Check Environment Variables
        run: echo "${{ vars.RAND }}"
